### ISSUE TITLE
Failed building wheel for AccessControl 4.4 (Plone 5.2.14)

### ISSUE THREAD

**Issue by ksuess** [zopefoundation/AccessControl#160] opened 2024-11-13 19:08 UTC
## BUG/PROBLEM REPORT / FEATURE REQUEST

buildout of Plone 5.2.14 fails with:

_ERROR: Failed building wheel for AccessControl_

https://gist.github.com/ksuess/fdee1e1915c1cfc5687271493b725160

### What version of Python and Zope/Addons I am using:

- MacOS 15
- Python 3.8.19
- Plone 5.2.14

Any hint how to fix this is welcome.

**Comment by davisagli** [comment] 2024-11-13 19:14
@ksuess This is a duplicate of #149. It was already fixed in recent versions of AccessControl. You can't use recent versions of AccessControl with this old version of Plone, but there is a workaround: https://github.com/zopefoundation/AccessControl/issues/149#issuecomment-2166161657

**Closed by davisagli** 2024-11-13 19:14 UTC

**Comment by petschki** [comment] 2024-12-20 09:16
Just got bitten by this too here on ARM MacOS `15.1.1`, python `3.8.20`, Plone `5.2.15` ... I can confirm, that `AccessControl==4.4` can be built with `CFLAGS="-Wno-error=int-conversion"` environment var.

**Comment by dataflake** [comment] 2024-12-20 09:21
We are phasing out support for Python 3.8 very soon, so this will most likely not be fixed.
