### ISSUE TITLE
Error in has_permission if current user is zope admin user

### ISSUE THREAD

**Issue by mcasagrande18** [zopefoundation/AccessControl#130] opened 2022-06-09 09:18 UTC
If I check permission passing user and the current user is zope admin user:
```python
api.user.has_permission('Manage portal', user=api.user.get_current(), obj=self.context)
```
then function throw this error: 
```
AccessControl-5.3-py3.9-linux-x86_64.egg/AccessControl/ImplPython.py", line 523, in checkPermission
    return context.user.allowed(object, roles)
AttributeError: 'MemberData' object has no attribute 'allowed'
```
if I don't pass the user works:
```python
api.user.has_permission('Manage portal', obj=self.context)
```

- Python: 3.9
- Plone: 6.0.0a4

**Comment by dataflake** [comment] 2022-06-09 09:38
The error tells you what happened. You're passing something that `AccessControl` doesn't expect, in this case a Plone `MemberData` object. This cannot work. You must pass a "real" Zope user object instead.

**Comment by ale-rt** [comment] 2022-06-09 09:43
Just change it to:
```
api.user.has_permission('Manage portal', obj=self.context)
```

See: https://docs.plone.org/develop/plone.api/docs/api/user.html#plone.api.user.has_permission

> Arguments username and user are mutually exclusive. You can either set one or the other, but not both. if username and user are not given, the authenticated member will be used.

**Comment by dataflake** [comment] 2022-06-09 09:45
Thanks @ale-rt for the explanation, I am not firm in Plone internals. Since this isn't an issue here I will close it.

**Closed by dataflake** 2022-06-09 09:45 UTC
Labels: invalid

**Comment by reinhardt** [comment] 2022-06-10 09:33
> See: https://docs.plone.org/develop/plone.api/docs/api/user.html#plone.api.user.has_permission

The documentation you're linking to says it expects a `MemberData` object:

> user (MemberData object) – User object for which you want to check the permission.

Is that a mistake in the documentation then?

**Comment by reinhardt** [comment] 2022-06-14 11:50
FTR, I've done some testing and found that passing in a `MemberData` to `has_permission` is not a problem and works in general. I have seen the above error before (but can't reproduce it right now), so maybe not passing in a user is the more robust variant.
